---
linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
  gofumpt:
    extra-rules: true
  govet:
    check-shadowing: true

issues:
  fix: false

output:
  sort-results: true

run:
  go: "1.20"
  timeout: 15m
