name: Test CI

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '*'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello, world!"
