on:
  push:
    branches:
      - main

jobs:
  in-container:
    name: Run things inside a container
    runs-on: ubuntu-latest
    container: docker.io/library/alpine:3.19
    steps:
      # Use a premade GitHub Action inside the container
      - uses: actions/checkout@v4

      # Use another GitHub Action to get a CLI.
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'

      # Use a different container image for the specific step.
      # Does the cloned repository exist here?
      - uses: docker://docker.io/nixos/nix:2.22.1
        with:
          entrypoint: ''
          args: /bin/sh -c "ls -la && nix --version"

      # Confirm we are on Alpine 3.19 and go is present
      - run: |
          apk info
          go version

      # Will the installed stuff in the above step persist here?
      - uses: docker://docker.io/library/node:20-bullseye
        with:
          entrypoint: ''
          args: /bin/sh -c "node --version && go version && go mod download"
